perfetto_cmd: Resolve missing O_CREAT mode
 src/perfetto_cmd/perfetto_cmd.cc:359:65:
  error: 'open' has superfluous mode bits; missing O_CREAT?

Change-Id: Id051a878a93268c42cd4d3e664247b98ed40dc25